// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MZwuxp4dzxTX3joqlC3p1922kW7qLPw',
    appId: '1:1085755773137:web:75deb6d1d7161eedd235f0',
    messagingSenderId: '1085755773137',
    projectId: 'fire-flutter-fdfd0',
    authDomain: 'fire-flutter-fdfd0.firebaseapp.com',
    storageBucket: 'fire-flutter-fdfd0.appspot.com',
    measurementId: 'G-3QGYS3DB2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4T87wJZ3cm0z_NIYSmu21D1iN66WmCcg',
    appId: '1:1085755773137:android:b476a1422b792f6fd235f0',
    messagingSenderId: '1085755773137',
    projectId: 'fire-flutter-fdfd0',
    storageBucket: 'fire-flutter-fdfd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTvajDkOHcuWdTXzmXmGtpkLCYVG52og',
    appId: '1:1085755773137:ios:3eeb736f4642bbe1d235f0',
    messagingSenderId: '1085755773137',
    projectId: 'fire-flutter-fdfd0',
    storageBucket: 'fire-flutter-fdfd0.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqTvajDkOHcuWdTXzmXmGtpkLCYVG52og',
    appId: '1:1085755773137:ios:5f6428a1626e3c44d235f0',
    messagingSenderId: '1085755773137',
    projectId: 'fire-flutter-fdfd0',
    storageBucket: 'fire-flutter-fdfd0.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
